# Generated by Django 5.2.1 on 2025-05-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='user',
        ),
    ]
